spring:
  application:
    name: customer-transaction
  data:
    mongodb:
      database: devdb
      uri: mongodb://localhost/devdb
  graphql:
    graphiql:
      enabled: true
      path: /graphiql
    path: /graphql
  security:
    user:
      name: zjh
      password: abc123
  autoconfigure:
    exclude:
      - org.springframework.cloud.netflix.eureka.EurekaDiscoveryClientConfiguration
      - org.springframework.cloud.netflix.eureka.EurekaClientAutoConfiguration
      - org.springframework.boot.actuate.autoconfigure.tracing.zipkin.ZipkinAutoConfiguration
management:
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
  tracing:
    sampling:
      probability: 1.0
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka
    healthcheck:
      enabled: true
    register-with-eureka: true
    fetch-registry: true
server:
  port: 8001
logging:
  pattern:
    level: ${spring.application.name:},%X{traceId:-},%X{spanId:-}
